apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nmar.fullname" . }}-core
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nmar.name" . }}-core
  template:
    metadata:
      labels:
        app: {{ include "nmar.name" . }}-core
    spec:
      containers:
      - name: core
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: MODEL_SERVER_URL
          value: "http://{{ include "nmar.name" . }}-model-server:8080"
        resources:
{{ toYaml .Values.resources | indent 10 }}
