apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nmar.fullname" . }}-model-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "nmar.name" . }}-model-server
  template:
    metadata:
      labels:
        app: {{ include "nmar.name" . }}-model-server
    spec:
      containers:
      - name: model-server
        image: "{{ .Values.modelServer.image }}:{{ .Values.modelServer.tag | default "latest" }}"
        ports:
        - containerPort: 8080
        resources:
{{ toYaml .Values.resources | indent 10 }}
